In [5]:
import pandas as pd

# Load your CSV
data = pd.read_csv("jobs_data.csv")

# Check the first few rows
data.head()

,job_title,url,posted_date,job_country_code,is_remote,employment_status,seniority,job_location,job_description,salary,...,hiring_manager_linkedin_url,company_name,company_url,company_linkedin_url,company_industry,company_employee_count,company_revenue_usd,company_seo_description,company_description,company_city
0,Search Technology Developer,https://in.linkedin.com/jobs/view/search-techn...,2026-03-17,IN,True,full_time,mid_level,"India, Madhya Pradesh, India",**Role Summary**\nWe are seeking a\n**Search T...,NaN,...,NaN,Papigen,https://papigen.com,https://www.linkedin.com/company/about-papigen/,IT Services and IT Consulting,8.0,NaN,Empowering future generations with smart techn...,Papigen is a world-class technology services b...,Dover
1,Senior Agentic AI / RAG Engineer,https://in.linkedin.com/jobs/view/senior-agent...,2026-03-17,IN,False,full_time,senior,"Vapi, Gujarat, India",**Role Overview**\n\nWe are looking for a\n**S...,NaN,...,https://www.linkedin.com/in/jay-kangriwala-45a...,Meril,https://merillife.com,https://www.linkedin.com/company/meril/,Medical Equipment Manufacturing,6351.0,NaN,More to Life,"Meril’s core objective is to design, manufactu...",Vapi
2,Java API + Kafka Developer,https://www.naukri.com/job-listings-java-api-k...,2026-03-17,IN,False,full_time,mid_level,"Gurugram, Haryana, India","**Roles and Responsibilities :**\n\n- Design, ...",Not Disclosed,...,NaN,Sun Life Global Solutions,NaN,NaN,Insurance Carriers,NaN,NaN,NaN,NaN,NaN
3,Java Developer - Ukranian (Remote),https://dk.linkedin.com/jobs/view/java-develop...,2026-03-17,DK,True,contract,mid_level,Denmark,**Top 1% Coders Needed - Shape AI future with ...,NaN,...,NaN,Quik Hire Staffing,https://quik-hire.com,https://in.linkedin.com/company/quik-hire-staf...,NaN,5.0,NaN,Your Quick Path to Quality Talent,Quik Hire Staffing Solutions is dedicated to h...,Pune
4,InDesign Developer / UI-UX & Graphic Design Pr...,http://in.indeed.com/job/indesign-developer-ui...,2026-03-17,IN,False,full_time,mid_level,"State of Mahārāshtra, India",Hiring: *InDesign Developer / UI-UX & Graphic ...,NaN,...,NaN,ENHANCE PLUS CONSULTANT,NaN,NaN,Staffing and Recruiting,NaN,NaN,NaN,NaN,NaN

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2242 entries, 0 to 2241
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   job_title                    2242 non-null   object
 1   url                          2242 non-null   object
 2   posted_date                  2242 non-null   object
 3   job_country_code             2242 non-null   object
 4   is_remote                    2242 non-null   bool
 5   employment_status            2214 non-null   object
 6   seniority                    2242 non-null   object
 7   job_location                 2242 non-null   object
 8   job_description              2242 non-null   object
 9   salary                       126 non-null    object
 10  hiring_manager_full_name     150 non-null    object
 11  hiring_manager_first_name    150 non-null    object
 12  hiring_manager_role          69 non-null     object
 13  hiring_manager_linkedin_url  150 non-null    object
 14  company_name                 2242 non-null   object
 15  company_url                  2145 non-null   object
 16  company_linkedin_url         2115 non-null   object
 17  company_industry             759 non-null    object
 18  company_employee_count       2115 non-null   float64
 19  company_revenue_usd          293 non-null    float64
 20  company_seo_description      2085 non-null   object
 21  company_description          1689 non-null   object
 22  company_city                 1753 non-null   object
dtypes: bool(1), float64(2), object(20)
memory usage: 387.7+ KB

In [7]:
data.describe()

       company_employee_count  company_revenue_usd
count             2115.000000         2.930000e+02
mean             14139.243026         2.307415e+10
std              41773.479675         1.444613e+10
min                  1.000000         3.100000e+05
25%                  5.000000         3.597500e+09
50%                  5.000000         3.250413e+10
75%                 54.000000         3.250413e+10
max             141397.000000         3.250413e+10

In [1]:
import pandas as pd

# Load your CSV
data = pd.read_csv("naukari_jobs_data_lakhs.csv")

# Check the first few rows
data.head()

FileNotFoundError: [Errno 2] No such file or directory: 'naukari_jobs_data_lakhs.csv'

In [8]:
data.shape

(2242, 23)